package observability

import "go.opentelemetry.io/otel/attribute"

const (
	SpanDBProgramDeleteEndedBefore        = "db.program.delete_ended_before"
	SpanDBProgramReplaceServicePrograms   = "db.program.replace_service_programs"
	SpanDBProgramUpsertAll                = "db.program.upsert_all"
	SpanDBServiceEPGSummary               = "db.service.epg_summary"
	SpanDBServiceReplaceChannelServices   = "db.service.replace_channel_services"
	SpanEPGCollectServiceSnapshots        = "epg.collect_service_snapshots"
	SpanEPGGatherCandidate                = "epg.gather_candidate"
	SpanEPGGatherNetwork                  = "epg.gather_network"
	SpanEPGMergeServicePrograms           = "epg.merge_service_programs"
	SpanEPGReplaceRemoteServicePrograms   = "epg.replace_remote_service_programs"
	SpanEPGSyncStoredServicePrograms      = "epg.sync_stored_service_programs"
	SpanJobRun                            = "job.run"
	SpanRemoteListServicePrograms         = "remote.list_service_programs"
	SpanRemoteScanServices                = "remote.scan_services"
	SpanRemoteStreamProgramEventsConnect  = "remote.stream_program_events.connect"
	SpanServiceScanReplaceChannelServices = "service_scan.replace_channel_services"
	SpanServiceScanRunScanner             = "service_scan.run_scanner"
	SpanServiceScanScanChannel            = "service_scan.scan_channel"
	SpanStreamGetOrCreate                 = "stream.get_or_create"
	SpanStreamSourceAcquire               = "stream.source.acquire"
	SpanStreamSourceSelectRoute           = "stream.source.select_route"
	SpanStreamSourceTryRoute              = "stream.source.try_route"
	SpanTunerAcquireDevice                = "tuner.acquire_device"
	SpanTunerProcessStart                 = "tuner.process.start"
	SpanTunerProcessStartWithRetry        = "tuner.process.start_with_retry"
)

const (
	AttrChannelID             attribute.Key = "channel.id"
	AttrChannelType           attribute.Key = "channel.type"
	AttrEPGCandidates         attribute.Key = "epg.candidates"
	AttrEPGNetworkID          attribute.Key = "epg.network_id"
	AttrEPGRetrievalTimeMS    attribute.Key = "epg.retrieval_time_ms"
	AttrEPGServiceID          attribute.Key = "epg.service_id"
	AttrEPGServices           attribute.Key = "epg.services"
	AttrEPGStaleAfter         attribute.Key = "epg.stale_after"
	AttrJobID                 attribute.Key = "job.id"
	AttrJobKey                attribute.Key = "job.key"
	AttrJobName               attribute.Key = "job.name"
	AttrJobRetryCount         attribute.Key = "job.retry_count"
	AttrProgramCount          attribute.Key = "program.count"
	AttrProgramCutoff         attribute.Key = "program.cutoff"
	AttrProgramFrom           attribute.Key = "program.from"
	AttrRemoteURL             attribute.Key = "remote.url"
	AttrRouteChannel          attribute.Key = "route.channel"
	AttrRouteCount            attribute.Key = "route.count"
	AttrRouteRemote           attribute.Key = "route.remote"
	AttrRouteType             attribute.Key = "route.type"
	AttrServiceCount          attribute.Key = "service.count"
	AttrStartupRetry          attribute.Key = "startup_retry"
	AttrStartupRetryMax       attribute.Key = "startup_retry.max"
	AttrStartupRetryTimeoutMS attribute.Key = "startup_retry.timeout_ms"
	AttrStreamActiveSession   attribute.Key = "stream.active_session"
	AttrTunedChannelID        attribute.Key = "tuned.channel.id"
	AttrTunedChannelType      attribute.Key = "tuned.channel.type"
	AttrWait                  attribute.Key = "wait"
)
